# Generated by Django 5.2.3 on 2025-06-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF file uploaded by the user', upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the PDF was uploaded')),
                ('name', models.CharField(blank=True, help_text='Name of the uploaded PDF', max_length=255, null=True)),
            ],
        ),
    ]
