# Generated by Django 5.2.3 on 2025-06-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(help_text='The query asked by the user')),
                ('response', models.TextField(blank=True, help_text='The response provided by the system', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the query was made')),
                ('pdf', models.ForeignKey(help_text='PDF related to this query', on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='retrival.uploadedpdf')),
            ],
        ),
    ]
